### ISSUE TITLE
editor

### ISSUE THREAD

**Issue by RequestKing** [ZeromusXYZ/AAEmu-Packer#6]
Hi

Can I request for .med editor of this game? (It has a "TheDarkLegions.med" file)

https://store.steampowered.com/app/492530/The_Dark_Legions/

**Comment by ZeromusXYZ** [comment]
This is not a XLGames game, so it likely uses a very different than what I'm using here for ArcheAge. If this is made using a specific game engine, you might be able to find editor for it.

I also don't really take requests for things not related to projects I work on myself.

I will close this issue, and wish you the best of luck in your search for a editor for this game.
